<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Baskervville&family=Noto+Sans+JP:wght@100;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/custom.css">
    <link rel="stylesheet" href="css/download.css">
    <link rel="stylesheet" href="css/form.css">
    <link rel="stylesheet" href="css/footer.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
    <!-- <img id="navlogo" src="images/logoplaceholder.svg" /> -->
    <ul id="navlinks">
        <li><a href="#home">Home</a></li>
        <li><a href="#news">News</a></li>
        <li><a href="#download">Download PDF</a></li>
        <li><a href="#form">Voorkeuren</a></li>
    </ul>
    <img id="menu-icon" src="images/menuplaceholder.png" />
    <div class="header-background">
        <div class="image-background"></div>
    </div>
    <!-- <div class="container blok1 text-center">
        LA GARe USP's <br/>

    </div> -->

    <div class="container-fluid blok2">
        <div class="row">
            <div class="col-lg-7">
                <span class="helper"></span><img src="images/blok2.jpg" />
            </div>
            <div class="col-lg-5 tekstblok" style="margin-top: 25px;">
                <div class="streep"></div><br />
                <h1 class="title">LA GARE</h1>
                <p class="subtitle">DE GEZELLIGE DORPSKERN AAN JE VOETEN</p>

                <p class="text">
                    <span class="text-semi">Algemene introtekst.</span> La Gare prachtig gelegen in Laren, een groene
                    en ruime omgeving met de dorpskern aan je voeten, waar het altijd
                    gezellig is. Karakteristiek dorp | goed bereikbaar met de auto (verbin-
                    dingen naar Amsterdam, Hilversum etc) | gemoedelijk | zeer groene
                    omgeving | knus en gezellig. Winkelen, horeca en cultuur. Luxe appar-
                    tementen, uitmundende afwerking, veel ruimte, natuur, stad dichtbij...
                    Fugitae non corro debit faceati antorporis natis que nis rat reptur. OIs
                    aut iliquid mi, cum re natenient et lit, officia ssimolo rporia dolore-
                    peliat et, ius il illore, optat il ipicipsusci quistio officae pediatia idAlia
                    cus magnis volessuntem faccus rercipiet molorep udisciisimus si cum,
                    cuptatiis si dem fugitio ratectet volorae. Itae essimus molore cus eap.
                </p>
            </div>
        </div>
    </div>

    <div class="container-fluid quote">
        <div class="row">
            <div class="col text-center vertical-center">
                "QUOTE over beide pagina's
                als hoofdstukverdeling
                omdat we hier dieper ingaan
                op het project ivm architectuur."
            </div>
        </div>
    </div>

    <div class="container-fluid blok2">
        <div class="row">
            <div class="col-lg-5 tekstblok">
                <div class="streep"></div><br />

                <h1 class="title">LA GARE</h1>
                <p class="subtitle">DE GEZELLIGE DORPSKERN AAN JE VOETEN</p>

                <p class="text">
                    <span class="text-semi">Algemene introtekst.</span> La Gare prachtig gelegen in Laren, een groene
                    en ruime omgeving met de dorpskern aan je voeten, waar het altijd
                    gezellig is. Karakteristiek dorp | goed bereikbaar met de auto (verbin-
                    dingen naar Amsterdam, Hilversum etc) | gemoedelijk | zeer groene
                    omgeving | knus en gezellig. Winkelen, horeca en cultuur. Luxe appar-
                    tementen, uitmundende afwerking, veel ruimte, natuur, stad dichtbij...
                    Fugitae non corro debit faceati antorporis natis que nis rat reptur. OIs
                    aut iliquid mi, cum re natenient et lit, officia ssimolo rporia dolore-
                    peliat et, ius il illore, optat il ipicipsusci quistio officae pediatia idAlia
                    cus magnis volessuntem faccus rercipiet molorep udisciisimus si cum,
                    cuptatiis si dem fugitio ratectet volorae. Itae essimus molore cus eap.
                </p>
            </div>
            <div class="col-lg-7">
                <span class="helper"></span><img src="images/blok2.jpg" />
            </div>
        </div>
    </div>

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="images/blok2.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="images/TEST.png" alt="Second slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

    <div class="container-fluid" id="download">
        <div class="row">
            <div class="col text-center">
                <form method="get" action="boek.pdf">
                    <button type="submit">Download!</button>
                </form>
            </div>
        </div>
    </div>

    <div class="container-fluid" id="form">


        <form action="form.phtml" method="post">
            <div class="form-row">

                <div class="form-group col-sm-6">
                    <label for="exampleFormControlInput1">Voornaam</label>
                    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Uw voornaam" name="firstname">
                </div>
                <div class="form-group col-sm-6">
                    <label for="exampleFormControlInput1">Achternaam</label>
                    <input type="text" class="form-control" id="exampleFormControlInput2" placeholder="Uw Achternaam" name="lastname">
                </div>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Emailadres</label>
                <input type="email" class="form-control" id="exampleFormControlInput3" placeholder="lagare@voorbeeld.nl" name="email">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Voorkeur 1:</label>
                <select class="form-control" id="exampleFormControlSelect1" name="select1">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect2">Voorkeur 2:</label>
                <select class="form-control" id="exampleFormControlSelect2" name="select2">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect2">Voorkeur 3</label>
                <select class="form-control" id="exampleFormControlSelect3" name="select3">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Verstuur</button>
        </form>

    </div>

    </div>

    <footer>
        <p class="text-center">Footer</p>
    </footer>




</body>

</html>